# Generated by Django 4.0.5 on 2022-07-05 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('success_deal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='successdeal',
            name='unique_user_product_review',
        ),
        migrations.RemoveField(
            model_name='successdeal',
            name='product',
        ),
        migrations.RemoveField(
            model_name='successdeal',
            name='user',
        ),
        migrations.AddField(
            model_name='successdeal',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_buyer', to=settings.AUTH_USER_MODEL, verbose_name='구매자'),
        ),
        migrations.AddField(
            model_name='successdeal',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_seller', to=settings.AUTH_USER_MODEL, verbose_name='판매자'),
        ),
        migrations.AddConstraint(
            model_name='successdeal',
            constraint=models.UniqueConstraint(fields=('buyer', 'seller'), name='unique_user_product_review'),
        ),
    ]
