# Generated by Django 4.0.5 on 2022-07-05 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('success_deal', '0002_remove_successdeal_unique_user_product_review_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='successdeal',
            name='unique_user_product_review',
        ),
        migrations.AddField(
            model_name='successdeal',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_product', to='product.product', verbose_name='상품'),
        ),
        migrations.AddConstraint(
            model_name='successdeal',
            constraint=models.UniqueConstraint(fields=('buyer', 'product'), name='unique_user_product_review'),
        ),
    ]
