# Generated by Django 4.0.3 on 2022-06-29 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='관심 목록')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='hobby',
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(to='user.watchlist', verbose_name='관심 목록'),
        ),
    ]
