# Generated by Django 4.0.5 on 2022-06-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_watchlist_remove_userprofile_hobby_delete_hobby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deal_reliability_avg',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3, verbose_name='거래 신뢰도'),
        ),
    ]
