# Generated by Django 4.0.5 on 2022-07-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_deal_reliability_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='deal_reliability_avg',
            field=models.IntegerField(default=5, verbose_name='거래 신뢰도'),
        ),
    ]
